#ifndef ANTZDATATRANSFORM_GLOBAL_H
#define ANTZDATATRANSFORM_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef ANTZDATATRANSFORM_LIB
# define ANTZDATATRANSFORM_EXPORT Q_DECL_EXPORT
#else
# define ANTZDATATRANSFORM_EXPORT Q_DECL_IMPORT
#endif

#endif // ANTZDATATRANSFORM_GLOBAL_H
