/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class synglyphx_util_ConvertHash */

#ifndef _Included_synglyphx_util_ConvertHash
#define _Included_synglyphx_util_ConvertHash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     synglyphx_util_ConvertHash
 * Method:    getHash
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_synglyphx_util_ConvertHash_getHash
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
