#include "changedatasourcefiledialog.h"
#include <QtCore/QFile>
#include <QtCore/QDir>
#include "databaseinfo.h"

namespace SynGlyphX {

	ChangeDatasourceFileDialog::ChangeDatasourceFileDialog(const SynGlyphX::FileDatasource& oldDatasourceFile, const QString& acceptButtonText, QWidget *parent)
		: ReplaceFilenameDialog(QString::fromStdWString(oldDatasourceFile.GetDBName()), acceptButtonText, parent),
		m_fileSourceType(oldDatasourceFile.GetType())
	{
		setWindowTitle(tr("Change Datasource File"));

		if (oldDatasourceFile.CanDatasourceHaveMultipleTables()) {

			for (std::wstring table : oldDatasourceFile.GetTables()) {

				m_oldDatasourceTables.append(QString::fromStdWString(table));
			}
			m_oldDatasourceTables.sort();
		}
	}

	ChangeDatasourceFileDialog::~ChangeDatasourceFileDialog()
	{

	}

	bool ChangeDatasourceFileDialog::IsNewFileValid() const {

		QString newDatasource = m_newDatasourceFileLineEdit->GetText();

		if (m_fileSourceType == SynGlyphX::FileDatasource::SourceType::SQLITE3) {

			if (SynGlyphX::DatabaseInfo::IsSQLiteDB(newDatasource)) {

				QStringList tables = SynGlyphX::DatabaseInfo::GetListOfTablesWithoutAutogeneratedTablesInDatabaseFile(newDatasource);
				tables.sort();
				return (m_oldDatasourceTables == tables);
			}
		}
		else if (m_fileSourceType == SynGlyphX::FileDatasource::SourceType::CSV) {

			if (newDatasource.right(4) == ".csv") {

				QFile csvFile(newDatasource);
				QFile csvtFile(newDatasource + 't');

				if (csvFile.exists() && csvtFile.exists()) {

					return true;
				}
			}
		}

		return false;
	}

} //namespace SynGlyphX