#ifndef SGXDATATRANSFORMGUI_GLOBAL_H
#define SGXDATATRANSFORMGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef WIN32
#ifdef SGXDataTransformGUI_EXPORTS
# define SGXDATATRANSFORMGUI_EXPORT Q_DECL_EXPORT
#else
# define SGXDATATRANSFORMGUI_EXPORT Q_DECL_IMPORT
#endif

#else
# define SGXDATATRANSFORMGUI_EXPORT
#endif

#endif // SGXDATATRANSFORMGUI_GLOBAL_H
