#ifndef SGXDATATRANSFORMGUI_GLOBAL_H
#define SGXDATATRANSFORMGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SGXDATATRANSFORMGUI_LIB
# define SGXDATATRANSFORMGUI_EXPORT Q_DECL_EXPORT
#else
# define SGXDATATRANSFORMGUI_EXPORT Q_DECL_IMPORT
#endif

#endif // SGXDATATRANSFORMGUI_GLOBAL_H
