#ifndef DATABASESERVICES_H
#define DATABASESERVICES_H

#include "sgxdatatransform_global.h"
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtSql/QSqlDatabase>
#include "datasource.h"
#include "datatransformmapping.h"
#include <boost/uuid/uuid.hpp>
#include "inputfield.h"

namespace SynGlyphX {

	class SGXDATATRANSFORM_EXPORT DatabaseServices
	{
	public:
		DatabaseServices();
		~DatabaseServices();

		static bool IsSQLiteDB(const QString& filename);

		static QString GetFormattedDBName(const QSqlDatabase& db);
		static QString GetFormattedDBName(const boost::uuids::uuid& databaseID);

		static QStringList GetListOfTablesWithoutAutogeneratedTables(const QSqlDatabase& db);
		static QStringList GetListOfTablesWithoutAutogeneratedTables(const QString& dbName, SynGlyphX::Datasource::SourceType sourceType);

		static QString GetQtDBType(SynGlyphX::Datasource::SourceType sourceType);

		static void AddDatabaseConnections(const DataTransformMapping::DatasourceMap& datasources, unsigned int numNewDatasources);

		static QVariantList RunSqlQuery(const InputField& inputfield);

	private:

	};

} //namespace SynGlyphX

#endif //DATABASESERVICES_H