#ifndef SGXDATATRANSFORM_GLOBAL_H
#define SGXDATATRANSFORM_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SGXDATATRANSFORM_LIB
# define SGXDATATRANSFORM_EXPORT Q_DECL_EXPORT
#else
# define SGXDATATRANSFORM_EXPORT Q_DECL_IMPORT
#endif

#endif // SGXDATATRANSFORM_GLOBAL_H
