#ifndef DATABASESERVICES_H
#define DATABASESERVICES_H

#include "sgxdatatransform_global.h"
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtSql/QSqlDatabase>
#include <unordered_set>
#include "datasourcemaps.h"
#include <boost/uuid/uuid.hpp>
#include "inputfield.h"
#include "uuid.h"

namespace SynGlyphX {

	class SGXDATATRANSFORM_EXPORT SourceDataManager
	{
	public:
		SourceDataManager();
		~SourceDataManager();

		static bool IsSQLiteDB(const QString& filename);

		static QString GetFormattedDBName(const QSqlDatabase& db);
		static QString GetFormattedDBName(const boost::uuids::uuid& databaseID);

		static QStringList GetListOfTablesWithoutAutogeneratedTables(const QSqlDatabase& db);
		static QStringList GetListOfTablesWithoutAutogeneratedTablesInDatabaseFile(const QString& dbName);

		static QString GetQtDBType(const SynGlyphX::Datasource& datasource);
		static QStringList GetSQLiteDataTypesForFormat(const QString& format);

		QVariantList RunSelectSqlQuery(const InputField& inputfield) const;
		QVariantList GetMinMaxSqlQuery(const InputField& inputfield) const;

		void AddDatabaseConnection(const Datasource& datasource, const boost::uuids::uuid& datasourceID);
		void AddDatabaseConnections(const DatasourceMaps& datasources);
		void ClearDatabaseConnection(const boost::uuids::uuid& id);
		void ClearDatabaseConnections();

		void SetIntermediateDirectory(QString directory);

	private:
		void ClearDatabaseConnection(const QString& id);
		QString GetIntermediateSQLiteDB(const FileDatasource& datasource, const QString& connectionName);

		std::unordered_set<boost::uuids::uuid, SynGlyphX::UUIDHash> m_databaseIDs;
		QString m_intermediateDirectory;
	};

} //namespace SynGlyphX

#endif //DATABASESERVICES_H