///
/// SynGlyphX Holdings Incorporated ("COMPANY") CONFIDENTIAL
/// Copyright (c) 2013-2015 SynGlyphX Holdings Incorporated, All Rights Reserved.
///
/// NOTICE:  All information contained herein is, and remains the property of COMPANY. The intellectual and technical concepts contained
/// herein are proprietary to COMPANY and may be covered by U.S. and Foreign Patents, patents in process, and are protected by trade secret or copyright law.
/// Dissemination of this information or reproduction of this material is strictly forbidden unless prior written permission is obtained
/// from COMPANY.  Access to the source code contained herein is hereby forbidden to anyone except current COMPANY employees, managers or contractors who have executed 
/// Confidentiality and Non-disclosure agreements explicitly covering such access.
///
/// The copyright notice above does not evidence any actual or intended publication or disclosure  of  this source code, which includes  
/// information that is confidential and/or proprietary, and is a trade secret, of  COMPANY.   ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC  PERFORMANCE, 
/// OR PUBLIC DISPLAY OF OR THROUGH USE  OF THIS  SOURCE CODE  WITHOUT  THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED, AND IN VIOLATION OF APPLICABLE 
/// LAWS AND INTERNATIONAL TREATIES.  THE RECEIPT OR POSSESSION OF  THIS SOURCE CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS  
/// TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE, USE, OR SELL ANYTHING THAT IT  MAY DESCRIBE, IN WHOLE OR IN PART.                
///

#ifndef DATABASESERVICES_H
#define DATABASESERVICES_H

#include "sgxdatatransform_global.h"
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtSql/QSqlDatabase>
#include <unordered_set>
#include "datasourcemaps.h"
#include "csvfilereader.h"
#include "inputfield.h"
#include "uuid.h"

namespace SynGlyphX {

	class SGXDATATRANSFORM_EXPORT CSVCache {

	public:
		CSVCache();
		virtual ~CSVCache();

		virtual bool IsValid() const;
		void Setup(const QString& cacheFilename);
		void AddCSVFile(const QString& tableName, const QString& csvFilename);

	protected:
		virtual void CreateNewTableInCache(const QString& name, const QString& fieldNamesAndTypes);
		void CreateTableFromCSVHeaders(const QString& name, const CSVFileReader::CSVValues& headers, const CSVFileReader::CSVValues& types);
		void CommitChanges();

		QString m_connectionID;
		QSqlDatabase m_db;
	};

	class SGXDATATRANSFORM_EXPORT SourceDataManager
	{
	public:
		SourceDataManager();
		~SourceDataManager();

		static bool IsSQLiteDB(const QString& filename);

		static QStringList GetListOfTablesWithoutAutogeneratedTables(const QSqlDatabase& db);
		static QStringList GetListOfTablesWithoutAutogeneratedTablesInDatabaseFile(const QString& dbName);

		static QString GetQtDBType(const SynGlyphX::Datasource& datasource);
		static QStringList GetSQLiteDataTypesForFormat(const QString& format);

		static void SetIntermediateDirectory(const QString& directory);
		static const QString& GetIntermeidateDirectory();

		QVariantList RunSelectSqlQuery(const InputField& inputfield) const;
		QVariantList GetMinMaxSqlQuery(const InputField& inputfield) const;

		void AddDatabaseConnection(const Datasource& datasource, const boost::uuids::uuid& datasourceID);
		void AddDatabaseConnections(const DatasourceMaps& datasources);
		void ClearDatabaseConnection(const boost::uuids::uuid& id);
		void ClearDatabaseConnections();

	private:
		typedef std::unordered_set<boost::uuids::uuid, SynGlyphX::UUIDHash> DatabaseIDSet;
		QString GetIntermediateSQLiteDB(const FileDatasource& datasource, const QString& connectionName);
		void ClearDatabaseConnection(const DatabaseIDSet::const_iterator& id);

		DatabaseIDSet m_databaseIDs;
		static QString s_intermediateDirectory;
	};

} //namespace SynGlyphX

#endif //DATABASESERVICES_H