#ifndef MAPDOWNLOADING_GLOBAL_H
#define MAPDOWNLOADING_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MAPDOWNLOADING_LIB
# define MAPDOWNLOADING_EXPORT Q_DECL_EXPORT
#else
# define MAPDOWNLOADING_EXPORT Q_DECL_IMPORT
#endif

#endif // MAPDOWNLOADING_GLOBAL_H
