#ifndef SGXQTDBDRIVERS_GLOBAL_H
#define SGXQTDBDRIVERS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SGXQTDBDRIVERS_LIB
# define SGXQTDBDRIVERS_EXPORT Q_DECL_EXPORT
#else
# define SGXQTDBDRIVERS_EXPORT Q_DECL_IMPORT
#endif

#endif // SGXQTDBDRIVERS_GLOBAL_H
