#ifndef DATABASESERVICES_H
#define DATABASESERVICES_H

#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtSql/QSqlDatabase>
#include "datasource.h"
#include "datatransform.h"
#include <boost/uuid/uuid.hpp>

class DatabaseServices
{
public:
	DatabaseServices();
	~DatabaseServices();

	static bool IsSQLiteDB(const QString& filename);

	static QString GetFormattedDBName(const QSqlDatabase& db);
	static QString GetFormattedDBName(const boost::uuids::uuid& databaseID);

	static void RemoveAutoGeneratedTableNamesFromList(QStringList& list);

	static QString GetQtDBType(SynGlyphX::Datasource::SourceType sourceType);

	static void AddDatabaseConnections(const SynGlyphX::DataTransform::DatasourceMap& datasources, unsigned int numNewDatasources);

private:
	
};

#endif //DATABASESERVICES_H